/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComGen: typeof import('./components/com/ComGen.vue')['default']
    ComSkuCalc: typeof import('./components/com/ComSkuCalc.vue')['default']
    CusTabbar: typeof import('./components/cusTabbar.vue')['default']
    CusWxs: typeof import('./components/cusWxs.vue')['default']
    DaTree: typeof import('./components/da-tree/index.vue')['default']
    DymInput: typeof import('./components/dymInput.vue')['default']
    IconMask: typeof import('./components/iconMask.vue')['default']
    LinkScrollCom: typeof import('./components/linkScrollCom.vue')['default']
    ListChat: typeof import('./components/listChat.vue')['default']
    LockButton: typeof import('./components/LockButton.vue')['default']
    MpHtml: typeof import('./components/mp-html/mp-html.vue')['default']
    Navigatorbar: typeof import('./components/navigatorbar.vue')['default']
    Node: typeof import('./components/mp-html/node/node.vue')['default']
    NumberBox: typeof import('./components/NumberBox.vue')['default']
    OrderSku: typeof import('./components/OrderSku.vue')['default']
    PageLoading: typeof import('./components/pageLoading.vue')['default']
    PageWrapper: typeof import('./components/pageWrapper.vue')['default']
    PageWrapperDetail: typeof import('./components/pageWrapperDetail.vue')['default']
    PullList: typeof import('./components/pullList.vue')['default']
    ResendButton: typeof import('./components/ResendButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RtScroll: typeof import('./components/rt-scroll/rt-scroll.vue')['default']
    RtScrollY: typeof import('./components/custom/rt-scroll-y.vue')['default']
    ShopCard: typeof import('./components/ShopCard.vue')['default']
    SkuCart: typeof import('./components/SkuCart.vue')['default']
    SkuPage: typeof import('./components/SkuPage.vue')['default']
    Spacer: typeof import('./components/Spacer.vue')['default']
  }
}
